import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { cookies } from 'next/headers'
import "@app/styles/globals.scss"
import * as React from "react"
import StoreProvider from "./StoreProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const cookieStore = cookies()
  const localeCookie = cookieStore.get("NEXT_LOCALE")

  return (
    <html lang={localeCookie?.value ?? "en"}>
      <body className={inter.className}>
        <StoreProvider locale={localeCookie?.value ?? "en"}>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
