import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { cookies } from 'next/headers'
import "@app/styles/globals.scss"
import * as React from "react"
import StoreProvider from "./StoreProvider"
import DictionariesProvider from "./DictionariesProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const cookieStore = cookies()
  const locale = cookieStore.get("NEXT_LOCALE")?.value ?? "en"
  const token = cookieStore.get("jwtToken")?.value ?? ""

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <StoreProvider token={token} locale={locale}>
          <DictionariesProvider>
            {children}
          </DictionariesProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
